# Generated by Django 2.1.2 on 2018-10-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_newmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewModel',
            new_name='ModelBaru',
        ),
    ]
