# Generated by Django 2.1.2 on 2018-10-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181008_0351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelBaru',
        ),
    ]
