# Generated by Django 2.1.2 on 2018-10-08 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_delete_modelbaru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('ongkir', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qty', models.IntegerField(default=1)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('checkout', 'Checkout'), ('paid', 'Terbayar'), ('delivered', 'Terkirim')], default='checkout', max_length=10)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Produk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
