# Generated by Django 2.1.2 on 2018-10-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='no_hape',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
