# Generated by Django 2.1.2 on 2018-10-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_no_hape'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qty', models.IntegerField(default=1)),
                ('totalhargabarang', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='produk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='totalbelanja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='orderbarang',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Order'),
        ),
        migrations.AddField(
            model_name='orderbarang',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Produk'),
        ),
    ]
