# Generated by Django 2.1.2 on 2018-10-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20181024_0546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderbarang',
            unique_together={('order', 'produk')},
        ),
    ]
