# Generated by Django 2.1.2 on 2018-10-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20181029_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbarang',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbarangnya', to='product.Order'),
        ),
        migrations.AlterField(
            model_name='orderbarang',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbarangnya', to='product.Produk'),
        ),
    ]
