# Generated by Django 2.1.2 on 2018-10-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20181029_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbarang',
            name='totalhargabarang',
        ),
    ]
